In [1]:
%run useful_functions.py

C:\Users\natha\Desktop\17-Cyber-risk_and_the_cross-section_of_stock_returns-main\17-Cyber-risk_and_the_cross-section_of_stock_returns-main\Work_Nathan\useful_functions.py:943: SyntaxWarning: invalid escape sequence '\s'
  item1A = re.sub('\s{2,}',' ', item1A)
C:\Users\natha\Desktop\17-Cyber-risk_and_the_cross-section_of_stock_returns-main\17-Cyber-risk_and_the_cross-section_of_stock_returns-main\Work_Nathan\useful_functions.py:954: SyntaxWarning: invalid escape sequence '\s'
  document = re.sub('\s{2,}',' ', document)
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\natha\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

update 18

In [2]:
csv_file_path = '../../data/stocknames.csv.gz'

# Read the CSV file into a pandas DataFrame
stock_info = pd.read_csv(csv_file_path)

url_columns = [col for col in stock_info.columns if 'url' in col]
stock_info.drop(columns=url_columns, inplace=True)


# Display the DataFrame
display(stock_info)

,CIK,comnam,end_date,filling_date_2007,filling_date_2008,filling_date_2009,filling_date_2010,filling_date_2011,filling_date_2012,filling_date_2013,...,filling_date_2018,filling_date_2019,filling_date_2020,filling_date_2021,filling_date_2022,filling_date_2023,filling_date_2024,permco,st_date,ticker
0,1318605.0,TESLA INC,2023-12-29,NaN,NaN,NaN,NaN,2011-03-03,2012-02-27,2013-03-07,...,2018-02-23,2019-02-19,2020-02-13,2021-02-08,2022-02-07,2023-01-31,2024-01-29,53453,2010-06-29,TSLA
1,1123494.0,HARVARD BIOSCIENCE INC,2023-12-29,2007-03-15,2008-03-11,2009-03-11,2010-03-11,2011-03-16,2012-03-15,2013-03-18,...,2018-03-16,2019-03-18,2020-03-16,2021-03-12,2022-03-11,2023-03-09,NaN,41060,2000-12-07,HBIO
2,729580.0,BEL FUSE INC,2023-12-29,2007-03-16,2008-03-17,2009-03-13,2010-03-12,2011-03-11,2012-03-12,2013-03-12,...,2018-03-09,2019-03-08,2020-03-25,2021-03-12,2022-03-14,2023-03-10,NaN,6653,1983-12-06,BELFA
3,1899287.0,AMPRIUS TECHNOLOGIES INC,2023-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2023-03-30,NaN,59244,2022-09-15,AMPX
4,1468327.0,RENT THE RUNWAY INC,2023-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2022-04-14,2023-04-13,NaN,58882,2021-10-27,RENT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7078,1515114.0,GROUND WATER INDUSTRIES INC,1974-07-31,NaN,NaN,NaN,NaN,NaN,2012-07-16,2013-07-16,...,NaN,NaN,NaN,NaN,2022-06-15,NaN,NaN,2067,1972-12-14,GWIN
7079,1394638.0,CLARCAN PETROLEUM CORP,1974-04-01,NaN,NaN,2009-01-28,2010-01-15,2011-04-27,2012-12-28,NaN,...,2018-01-04,2019-09-04,2020-12-30,NaN,2022-01-11,2023-01-13,NaN,23248,1973-02-09,CLCN
7080,1444839.0,BRAVO KNITS INC,1973-12-12,NaN,NaN,2009-07-17,2010-03-31,2011-03-31,2012-04-16,2013-04-16,...,NaN,2019-09-03,2020-03-17,2021-03-02,2022-02-17,2023-03-06,NaN,22896,1972-12-14,BRVO
7081,14073.0,BRESLER & REINER INC,1973-04-03,2007-04-02,2008-03-31,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22905,1972-12-14,BRER
7082,1068689.0,ATLANTIC DEPARTMENT STORES INC,1973-03-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2019-04-12,2020-04-17,2021-03-23,2022-03-31,2023-02-24,NaN,22619,1972-12-14,ATDS

In [3]:
ticker_list=stock_info.ticker.values

In [4]:
#create template for each score
# Generate index ranging from January 2007 to December 2024
dates = pd.date_range(start='2007-01-01', end='2024-12-31', freq='ME').strftime('%Y-%m')

# Create DataFrame with NaN values
template = pd.DataFrame(index=dates, columns=ticker_list)
template[:] = np.nan

In [5]:
def date_finder(ticker,year):
    column_filling_name="filling_date_"+str(year)
    # Find the corresponding value in column A where column B matches the value of reference
    date=stock_info.loc[stock_info['ticker'] == ticker, column_filling_name].values[0]

    if not isinstance(date, str):
        print(ticker)
        print(year)
        STOP

    return '-'.join(date.split('-')[:2])

In [6]:
def textual_score_template_construction(temp):


    readability_table=temp.copy(deep=True)
    secret_table=temp.copy(deep=True)
    risk_length_table=temp.copy(deep=True)
    

    histo_dict={}
    
    years=np.arange(2007,2025) #!!!!!!!!
    for year in years:
        print("starting year ",year," ...")
        directory='../../data/10k_statements_new/financial_text_variables/'+str(year)+'/'

        
        for matrix_name in tqdm(os.listdir(directory)):
            ticker=matrix_name.split('_')[0]
            if "TSLA" in matrix_name or "AAPL" in matrix_name or True:
                triple_score = np.load(directory+matrix_name)


                date_to_add=date_finder(ticker,year)
                

                readability_table.loc[date_to_add, ticker] = triple_score[0]
                secret_table.loc[date_to_add, ticker] = triple_score[1]
                risk_length_table.loc[date_to_add, ticker] = triple_score[2]
                
                            
    return readability_table, secret_table, risk_length_table

In [7]:
readability_table, secret_table, risk_length_table=textual_score_template_construction(template.copy(deep=True))

starting year  2007  ...

  0%|          | 0/3279 [00:00<?, ?it/s]

starting year  2008  ...

  0%|          | 0/3343 [00:00<?, ?it/s]

starting year  2009  ...

  0%|          | 0/3542 [00:00<?, ?it/s]

starting year  2010  ...

  0%|          | 0/3472 [00:00<?, ?it/s]

starting year  2011  ...

  0%|          | 0/3432 [00:00<?, ?it/s]

starting year  2012  ...

  0%|          | 0/3413 [00:00<?, ?it/s]

starting year  2013  ...

  0%|          | 0/3404 [00:00<?, ?it/s]

starting year  2014  ...

  0%|          | 0/3491 [00:00<?, ?it/s]

starting year  2015  ...

  0%|          | 0/3618 [00:00<?, ?it/s]

starting year  2016  ...

  0%|          | 0/3657 [00:00<?, ?it/s]

starting year  2017  ...

  0%|          | 0/3704 [00:00<?, ?it/s]

starting year  2018  ...

  0%|          | 0/3820 [00:00<?, ?it/s]

starting year  2019  ...

  0%|          | 0/3939 [00:00<?, ?it/s]

starting year  2020  ...

  0%|          | 0/4076 [00:00<?, ?it/s]

starting year  2021  ...

  0%|          | 0/4513 [00:00<?, ?it/s]

starting year  2022  ...

  0%|          | 0/5289 [00:00<?, ?it/s]

starting year  2023  ...

  0%|          | 0/4996 [00:00<?, ?it/s]

starting year  2024  ...

  0%|          | 0/2014 [00:00<?, ?it/s]

In [8]:
display(readability_table)
save_path_ratio='textual_scores_dataframes/'
readability_table.to_csv(save_path_ratio + 'readability_table.csv.gz')

,TSLA,HBIO,BELFA,AMPX,RENT,INLX,NTRS,PYXS,SPGI,XPER,...,FLYD,BCRD,MSPC,MSTC,HRST,GWIN,CLCN,BRVO,BRER,ATDS
2007-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2007-02,NaN,NaN,NaN,NaN,NaN,NaN,3891088,NaN,5242027,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2007-03,NaN,1283155,2718436,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2007-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1441898,NaN,NaN,NaN,3823546,NaN
2007-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
display(secret_table)
save_path_ratio='textual_scores_dataframes/'
secret_table.to_csv(save_path_ratio + 'secret_table.csv.gz')

,TSLA,HBIO,BELFA,AMPX,RENT,INLX,NTRS,PYXS,SPGI,XPER,...,FLYD,BCRD,MSPC,MSTC,HRST,GWIN,CLCN,BRVO,BRER,ATDS
2007-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2007-02,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2007-03,NaN,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2007-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN
2007-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
display(risk_length_table)
save_path_ratio='textual_scores_dataframes/'
risk_length_table.to_csv(save_path_ratio + 'risk_length_table.csv.gz')

,TSLA,HBIO,BELFA,AMPX,RENT,INLX,NTRS,PYXS,SPGI,XPER,...,FLYD,BCRD,MSPC,MSTC,HRST,GWIN,CLCN,BRVO,BRER,ATDS
2007-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2007-02,NaN,NaN,NaN,NaN,NaN,NaN,76,NaN,57,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2007-03,NaN,215,65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2007-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,308,NaN,NaN,NaN,99,NaN
2007-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN