In [1]:
%run useful_functions.py

C:\Users\natha\Desktop\17-Cyber-risk_and_the_cross-section_of_stock_returns-main\17-Cyber-risk_and_the_cross-section_of_stock_returns-main\Work_Nathan\useful_functions.py:943: SyntaxWarning: invalid escape sequence '\s'
  item1A = re.sub('\s{2,}',' ', item1A)
C:\Users\natha\Desktop\17-Cyber-risk_and_the_cross-section_of_stock_returns-main\17-Cyber-risk_and_the_cross-section_of_stock_returns-main\Work_Nathan\useful_functions.py:954: SyntaxWarning: invalid escape sequence '\s'
  document = re.sub('\s{2,}',' ', document)
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\natha\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

update 18

In [2]:
series_list=[]
for ticker in tqdm(os.listdir('Financial_values/')):
    try:
        directory='Financial_values/'+ticker+'/monthly_returns.csv'
        price_table = pd.read_csv(directory)
        
        #price_table['date'] = price_table['date'].apply(lambda x: x[:-3])
        price_table.set_index('date', inplace=True)
    
        price_table[ticker]=price_table['ret']
    
        prc_table=price_table[[ticker]]


    except FileNotFoundError:

        prc_table=pd.Series(name=ticker, index=pd.Index([], name='date'))
    
    series_list.append(prc_table)

  0%|          | 0/7083 [00:00<?, ?it/s]

In [3]:
return_table=pd.concat(series_list, axis=1)
return_table.sort_index(inplace=True)

In [4]:
display(return_table)
save_path_ratio='Financial_ratios/'
return_table.to_csv(save_path_ratio + 'returns_monthly.csv.gz')

,A,AA,AAAU,AAC,AACC,AACI,AADI,AAI,AAIC,AAL,...,ZVIA,ZVO,ZVXI,ZWRK,ZWS,ZY,ZYME,ZYNE,ZYXI,ZZ
date,,,,,,,,,,,,,,,,,,,,,
1925-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1926-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1926-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1926-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1926-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08,-0.005749,-0.166068,-0.012330,0.003756,NaN,0.006150,0.181989,NaN,0.002169,-0.120597,...,-0.075540,NaN,NaN,NaN,-0.024639,NaN,-0.029491,2.643836,-0.211066,NaN
2023-09,-0.076402,-0.033910,-0.047594,0.006548,NaN,0.006112,-0.231746,NaN,-0.073593,-0.130346,...,-0.136187,NaN,NaN,NaN,-0.054018,NaN,-0.124309,-0.041353,0.038961,NaN
2023-10,-0.073556,-0.114246,0.074003,0.001859,NaN,0.000000,-0.095041,NaN,-0.030374,-0.129586,...,-0.126126,NaN,NaN,NaN,-0.055675,NaN,0.107255,NaN,0.110000,NaN
2023-11,0.236335,0.047582,0.025426,NaN,NaN,0.007477,0.200913,NaN,0.130120,0.114798,...,0.108247,NaN,NaN,NaN,0.115646,NaN,0.263533,NaN,0.031532,NaN
2023-12,0.089718,0.265823,0.013390,NaN,NaN,-0.000928,-0.615970,NaN,NaN,0.105390,...,-0.065116,NaN,NaN,NaN,-0.001019,NaN,0.171364,NaN,0.188865,NaN